language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage coveralls

script:
  - coverage run -m --branch pytest -vs test
  - coverage report -m

after_success:
  - coveralls
